### PR TITLE
Get the gem name from the *.gemspec not the repo

### LINKED ISSUE #56: Overriding gem repos fail if the gem name doesn't match the repo name
If you are overriding a gem where the name of the gem doesn't match the name of the repo, e.g. repo: https://github.com/openshift/prometheus-alert-buffer-client-ruby; gem name: prometheus-alert-buffer-client

### PR DESCRIPTION
**Pull request by agrare**
There are some cases where the name of the gem differs from the name of
the repository.  In these cases it is better to get the gem name for the
overrides.rb file from the name of the gemspec than the repo name.

Fixes https://github.com/ManageIQ/manageiq-cross_repo/issues/56

### CODE REVIEW

File: lib/manageiq/cross_repo/runner.rb [hunk 1]
```diff
@@ -73,7 +73,11 @@ def generate_bundler_d
       if gem_repos.empty?
         FileUtils.rm_f override_path
       else
-        content = gem_repos.map { |gem| "ensure_gem \"#{gem.repo}\", :path => \"#{gem.path}\"" }.join("\n")
+        content = gem_repos.map do |gem|
+          # If there is a gemspec get the name of the gem from that instead of the repository
+          gem_name = gem.path.glob("*.gemspec")&.first&.basename(".gemspec") || gem.repo
```
Comment (Fryguy) [inline lib/manageiq/cross_repo/runner.rb:78]: The `&` after the glob isn't necessary as glob will always return an Array

**Comment by Fryguy** [comment]
Merging...the cited issue is super-minor.
